### ISSUE TITLE
Passing through additional options to Postgrex

### ISSUE THREAD

**Issue by thdxr** [alexdesousa/ayesql#22]
I need to be able to pass the `timeout` parameter.  Think it's as simple as modifying the runner to accept a timeout argument.  Will submit in a PR if that makes sense

**Comment by alexdesousa** [comment]
@thdxr Yes! This would be great! Right now the runner is limited due to this fact. At first glance, your suggestion checks out :)

**Comment by alexdesousa** [comment]
@thdxr I added this functionality in the latest version. Just pass `timeout` as an option. Let me know if that works for you :slightly_smiling_face:

**Comment by alexdesousa** [comment]
Fixed in #24
